blueprint:
  name: Sleep as Android MQTT actions
  description: Define actions based on Sleep As Android sensor states
  domain: automation
  source_url: https://github.com/MonkeyGoneWIld/Sleepppp/blob/main/full.yaml
  input:
    device:
      name: SleepAsAndroid device
      description: 'Device for Sleep as Android '
      selector:
        device:
          integration: sleep_as_android
    person:
      name: Person
      description: Person for checking state
      selector:
        entity:
          domain: person
    state:
      name: State
      description: Person must be in this state
      default: home
    sleep_tracking_started:
      name: sleep_tracking_started
      description: sleep_tracking_started event
      default: []
      selector:
        action: {}
mode: queued
max_exceeded: silent
trigger:
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sleep_tracking_started
  id: sleep_tracking_started
condition:
- condition: state
  entity_id: !input person
  state: !input state
action:
- choose:
  - conditions:
      condition: trigger
      id: sleep_tracking_started
    sequence: !input 'sleep_tracking_started'
