blueprint:
  name: Sleep as Android MQTT actions
  description: Define actions based on Sleep As Android sensor states
  domain: automation
  source_url: https://github.com/MonkeyGoneWIld/Sleepppp/blob/main/full.yaml
  input:
    device:
      name: SleepAsAndroid device
      description: 'Device for Sleep as Android '
      selector:
        device:
          integration: sleep_as_android
    person:
      name: Person
      description: Person for checking state
      selector:
        entity:
          domain: person
    state:
      name: State
      description: Person must be in this state
      default: home
    sleep_tracking_started:
      name: sleep_tracking_started
      description: sleep_tracking_started event
      default: []
      selector:
        action: {}
    sleep_tracking_stopped:
      name: sleep_tracking_stopped
      description: sleep_tracking_stopped event
      default: []
      selector:
        action: {}
    sleep_tracking_paused:
      name: sleep_tracking_paused
      description: sleep_tracking_paused event
      default: []
      selector:
        action: {}
    sleep_tracking_resumed:
      name: sleep_tracking_resumed
      description: sleep_tracking_resumed event
      default: []
      selector:
        action: {}
    alarm_snooze_clicked:
      name: alarm_snooze_clicked
      description: alarm_snooze_clicked event
      default: []
      selector:
        action: {}
    alarm_snooze_canceled:
      name: alarm_snooze_canceled
      description: alarm_snooze_canceled event
      default: []
      selector:
        action: {}
    time_to_bed_alarm_alert:
      name: time_to_bed_alarm_alert
      description: time_to_bed_alarm_alert event
      default: []
      selector:
        action: {}
    alarm_alert_start:
      name: alarm_alert_start
      description: alarm_alert_start event
      default: []
      selector:
        action: {}
    alarm_alert_dismiss:
      name: alarm_alert_dismiss
      description: alarm_alert_dismiss event
      default: []
      selector:
        action: {}
    alarm_skip_next:
      name: alarm_skip_next
      description: alarm_skip_next event
      default: []
      selector:
        action: {}
    show_skip_next_alarm:
      name: show_skip_next_alarm
      description: show_skip_next_alarm event
      default: []
      selector:
        action: {}
    rem:
      name: rem
      description: rem event
      default: []
      selector:
        action: {}
    smart_period:
      name: smart_period
      description: smart_period event
      default: []
      selector:
        action: {}
    before_smart_period:
      name: before_smart_period
      description: before_smart_period event
      default: []
      selector:
        action: {}
    lullaby_start:
      name: lullaby_start
      description: lullaby_start event
      default: []
      selector:
        action: {}
    lullaby_stop:
      name: lullaby_stop
      description: lullaby_stop event
      default: []
      selector:
        action: {}
    lullaby_volume_down:
      name: lullaby_volume_down
      description: lullaby_volume_down event
      default: []
      selector:
        action: {}
    deep_sleep:
      name: deep_sleep
      description: deep_sleep event
      default: []
      selector:
        action: {}
    light_sleep:
      name: light_sleep
      description: light_sleep event
      default: []
      selector:
        action: {}
    awake:
      name: awake
      description: awake event
      default: []
      selector:
        action: {}
    not_awake:
      name: not_awake
      description: not_awake event
      default: []
      selector:
        action: {}
    apnea_alarm:
      name: apnea_alarm
      description: apnea_alarm event
      default: []
      selector:
        action: {}
    antisnoring:
      name: antisnoring
      description: antisnoring event
      default: []
      selector:
        action: {}
    sound_event_snore:
      name: sound_event_snore
      description: sound_event_snore event
      default: []
      selector:
        action: {}
    sound_event_talk:
      name: sound_event_talk
      description: sound_event_talk event
      default: []
      selector:
        action: {}
    sound_event_cough:
      name: sound_event_cough
      description: sound_event_cough event
      default: []
      selector:
        action: {}
    sound_event_baby:
      name: sound_event_baby
      description: sound_event_baby event
      default: []
      selector:
        action: {}
    sound_event_laugh:
      name: sound_event_laugh
      description: sound_event_laugh event
      default: []
      selector:
        action: {}
    before_alarm:
      name: before_alarm
      description: before_alarm event
      default: []
      selector:
        action: {}
mode: queued
max_exceeded: silent
trigger:
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sleep_tracking_started
  id: sleep_tracking_started
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sleep_tracking_stopped
  id: sleep_tracking_stopped
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sleep_tracking_paused
  id: sleep_tracking_paused
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sleep_tracking_resumed
  id: sleep_tracking_resumed
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: alarm_snooze_clicked
  id: alarm_snooze_clicked
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: alarm_snooze_canceled
  id: alarm_snooze_canceled
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: time_to_bed_alarm_alert
  id: time_to_bed_alarm_alert
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: alarm_alert_start
  id: alarm_alert_start
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: alarm_alert_dismiss
  id: alarm_alert_dismiss
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: alarm_skip_next
  id: alarm_skip_next
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: show_skip_next_alarm
  id: show_skip_next_alarm
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: rem
  id: rem
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: smart_period
  id: smart_period
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: before_smart_period
  id: before_smart_period
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: lullaby_start
  id: lullaby_start
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: lullaby_stop
  id: lullaby_stop
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: lullaby_volume_down
  id: lullaby_volume_down
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: deep_sleep
  id: deep_sleep
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: light_sleep
  id: light_sleep
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: awake
  id: awake
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: not_awake
  id: not_awake
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: apnea_alarm
  id: apnea_alarm
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: antisnoring
  id: antisnoring
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sound_event_snore
  id: sound_event_snore
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sound_event_talk
  id: sound_event_talk
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sound_event_cough
  id: sound_event_cough
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sound_event_baby
  id: sound_event_baby
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: sound_event_laugh
  id: sound_event_laugh
- platform: device
  domain: sleep_as_android
  device_id: !input 'device'
  type: before_alarm
  id: before_alarm
condition:
- condition: state
  entity_id: !input person
  state: !input state
action:
- choose:
  - conditions:
      condition: trigger
      id: sleep_tracking_started
    sequence: !input 'sleep_tracking_started'
